name: WonderBagShop
version: 3
main: de.jatitv.wonderbagshop.main.Main
api-version: 1.16
depend:
  - Vault
softdepend:
  - Economy
  - EssentialsX
  - CMI
authors: [ JaTiTV ]
description: WonderBagShop von JaTiTV
commands:
  wonderbagshop:
  wbs:
  wbsrl:
permissions:
  wonderbagshop.command:
    default: op
  wonderbagshop.command.info:
    default: op
  wonderbagshop.command.reload:
    default: op
  wonderbagshop.admin:
    default: op