# ___________________________________________________________________________________
#  __          __             _           ____               _____ _
#  \ \        / /            | |         |  _ \             / ____| |
#   \ \  /\  / /__  _ __   __| | ___ _ __| |_) | __ _  __ _| (___ | |__   ___  _ __
#    \ \/  \/ / _ \| '_ \ / _` |/ _ \ '__|  _ < / _` |/ _` |\___ \| '_ \ / _ \| '_ \
#     \  /\  / (_) | | | | (_| |  __/ |  | |_) | (_| | (_| |____) | | | | (_) | |_) |
#      \/  \/ \___/|_| |_|\__,_|\___|_|  |____/ \__,_|\__, |_____/|_| |_|\___/| .__/
#                                                      __/ |                  | |
#                                                     |___/                   |_|
# ___________________________________________________________________________________

name: WonderBagShop
version: 0.6_Snapshot
main: de.jatitv.wonderbagshop.main.Main
api-version: 1.16
depend:
  - Vault
softdepend:
  - Economy
  - EssentialsX
  - CMI
authors: [ JaTiTV ]
description: WonderBagShop von JaTiTV
commands:
  wonderbagshop:
  wbs:
  wbsrl:
permissions:
  wonderbagshop.command:
    default: op
  wonderbagshop.command.info:
    default: op
  wonderbagshop.command.reload:
    default: op
  wonderbagshop.admin:
    default: op